name: Deploy artifacts with Maven
on:
  push:
    branches: [master]
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Java environment
        uses: actions/setup-java@v1
        with:
          java-version: 8
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC }}
          gpg-passphrase: MAVEN_CENTRAL_GPG_PASSPHRASE
      - name: Deploy SNAPSHOT / Release
        uses: camunda-community-hub/community-action-maven-release@v1.0.5
        with:
          release-version: ${{ github.event.release.tag_name }}
          release-profile: community-action-maven-release
          nexus-usr: ${{ secrets.NEXUS_USR }}
          nexus-psw: ${{ secrets.NEXUS_PSW }}
          maven-usr: ${{ secrets.MAVEN_CENTRAL_DEPLOYMENT_USR }}
          maven-psw: ${{ secrets.MAVEN_CENTRAL_DEPLOYMENT_PSW }}
          maven-gpg-passphrase: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-pattern: ./camunda-platform-to-cloud-adapter/target/nexus-staging/**/*.jar
          maven-additional-options: -f camunda-platform-to-cloud-adapter/pom.xml
        id: release
      - if: github.event.release
        name: Attach artifacts to GitHub Release (Release only)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.release.outputs.artifacts_archive_path }}
          asset_name: camunda-platform-to-cloud-adapter.zip
          asset_content_type: application/zip
  publish-modeler-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Plugin
        uses: thedoctor0/zip-release@master
        with:
          path: 'camunda-modeler-plugin-platform-to-cloud-converter'
          type: 'zip'
          filename: 'camunda-modeler-plugin-platform-to-cloud-converter.zip'
          exclusions: '*.git* /*node_modules/*'
      - if: github.event.release
        name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "camunda-modeler-plugin-platform-to-cloud-converter.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
