name: Deploy artifacts with Maven
on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC }}
          gpg-passphrase: MAVEN_CENTRAL_GPG_PASSPHRASE
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Export Maven Project Version
        run: echo "maven_project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Deploy SNAPSHOT / Release
        uses: camunda-community-hub/community-action-maven-release@v1
        with:
          maven-release-options: -Dspotless.apply.skip
          maven-additional-options: -Dspotless.apply.skip
          release-version: ${{ github.event.release.tag_name }}
          release-profile: community-action-maven-release
          nexus-usr: ${{ secrets.NEXUS_USR }}
          nexus-psw: ${{ secrets.NEXUS_PSW }}
          maven-usr: ${{ secrets.MAVEN_CENTRAL_DEPLOYMENT_USR }}
          maven-psw: ${{ secrets.MAVEN_CENTRAL_DEPLOYMENT_PSW }}
          maven-url: oss.sonatype.org
          maven-gpg-passphrase: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
          maven-auto-release-after-close: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: release
      - name: Push Worker Image (latest)
        run: docker push ghcr.io/camunda-community-hub/camunda-7-to-8-migration/diagram-converter:latest
      - if: (!github.event.release)
        name: Push Worker Image (tag)
        run: docker push ghcr.io/camunda-community-hub/camunda-7-to-8-migration/diagram-converter:${{ env.maven_project_version }}
      - name: Push Worker Image (tag)
        run: docker push ghcr.io/camunda-community-hub/camunda-7-to-8-migration/diagram-converter:${{ github.event.release.tag_name }}
        if: github.event.release
      - if: github.event.release
        name: Attach artifacts to GitHub Release (Release only)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.release.outputs.artifacts_archive_path }}
          asset_name: camunda-7-to-8-migration.zip
          asset_content_type: application/zip
  publish-modeler-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Plugin
        uses: thedoctor0/zip-release@master
        with:
          path: 'modeler-plugin-7-to-8-converter'
          type: 'zip'
          filename: 'modeler-plugin-7-to-8-converter.zip'
          exclusions: '*.git* /*node_modules/*'
      - if: github.event.release
        name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "modeler-plugin-7-to-8-converter.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
