name: Build, test and deploy artifacts with Maven
on:
  workflow_dispatch: { }
  release:
    types: [ published ]
  push:
    branches: [ main ]
jobs:
  publish-maven:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC }}
          gpg-passphrase: MAVEN_CENTRAL_GPG_PASSPHRASE
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PSW }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy SNAPSHOT / Release
        uses: camunda-community-hub/community-action-maven-release@v2
        with:
          maven-additional-options: -P!autoFormat
          release-version: ${{ github.event.release.tag_name }}
          nexus-usr: ${{ secrets.NEXUS_USR }}
          nexus-psw: ${{ secrets.NEXUS_PSW }}
          sonatype-central-portal-usr: ${{ secrets.COMMUNITY_HUB_MAVEN_CENTRAL_CP_USR }}
          sonatype-central-portal-psw: ${{ secrets.COMMUNITY_HUB_MAVEN_CENTRAL_CP_PSW }}
          maven-gpg-passphrase: ${{ secrets.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
          maven-auto-release-after-close: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: release
      - if: github.event.release == null
        name: Push Docker image Webapp -> ghcr.io | SNAPSHOT
        run: docker push ghcr.io/camunda-community-hub/camunda-7-to-8-migration/migration-analyzer:SNAPSHOT
      - if: github.event.release == null
        name: Push Docker image Webapp -> DockerHub | SNAPSHOT
        run: docker push camundacommunityhub/migration-analyzer:SNAPSHOT
      - if: github.event.release
        name: Push Docker image Webapp -> ghcr.io | RELEASE VERSION
        run: docker push ghcr.io/camunda-community-hub/camunda-7-to-8-migration/migration-analyzer:${{ github.event.release.tag_name }}
      - if: github.event.release
        name: Push Docker image Webapp -> DockerHub | RELEASE VERSION
        run: docker push camundacommunityhub/migration-analyzer:${{ github.event.release.tag_name }}
      - if: github.event.release
        name: Push Docker image Webapp -> ghcr.io | LATEST (only on release)
        run: docker push -q ghcr.io/camunda-community-hub/camunda-7-to-8-migration/migration-analyzer:latest
      - if: github.event.release
        name:  Push Docker image Webapp -> DockerHub | LATEST (only on release)
        run: docker push -q camundacommunityhub/migration-analyzer:latest
      - if: github.event.release
        name: Attach Java artifacts to GitHub Release (Release only)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.release.outputs.artifacts_archive_path }}
          asset_name: camunda-7-to-8-migration-analyzer-mvn-deployment-artifacts.zip
          asset_content_type: application/zip
      - if: github.event.release
        name: Upload Webapp JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./webapp/target/camunda-7-to-8-migration-analyzer-webapp.jar
          asset_name: camunda-7-to-8-migration-analyzer-webapp.jar
          asset_content_type: application/java-archive
      - if: github.event.release
        name: Upload CLI jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cli/target/camunda-7-to-8-migration-analyzer-cli.jar
          asset_name: camunda-7-to-8-migration-analyzer-cli.jar
          asset_content_type: application/java-archive
      - name: Publish Unit Test Results
        id: publish
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/target/surefire-reports/*.xml'
