version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  labels:
  - "dependencies"
  commit-message:
    prefix: "deps:"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  labels:
  - "dependencies"
  commit-message:
    prefix: "deps:"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  labels:
  - "dependencies"
  commit-message:
    prefix: "deps:"
