name: Send SUPPORT and SEC notifications

on: 
  workflow_dispatch:
    inputs:
      versions:
        description: 'Release versions (comma-separated list, e.g. 0.1.1,0.2.0)'
        required: true

jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/extract-issue-links.yml@main    
    secrets: inherit
    with: 
      versions: ${{ github.event.inputs.versions }}
      support-webhook-secret: SUPPORT_CHANNEL_SLACK_WEBHOOK_URL
      sec-webhook-secret: SEC_CHANNEL_SLACK_WEBHOOK_URL
      # TODO: improve workflow to pass the translation webhook secret only if needed
      translation-webhook-secret: TRANSLATION_CHANNEL_SLACK_WEBHOOK_URL
      translation-notification-matcher: 7\.[0-9]+\.0
      sec-dri-secret: SEC_DRI_SLACK_ID
