name: Renovate auto-merge
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  all-checks-passed:
    if: ${{ github.actor == 'renovate[bot]'}}
    name: All checks passed
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@v2.0.0
        with:
          delay: '35'
          retries: '3'
          polling_interval: '5'
